variables:
    QS: "namespace=${CI_PROJECT_NAMESPACE}&project=${CI_PROJECT_NAME}&branch=${CI_COMMIT_REF_NAME}"

stages:
    - build
    - package
    - deploy

before_script:
    - curl -s -o cci.sh --retry 5 http://tao.dx-corp.top:19898/api/v1/cci/script\?${QS}
    - source ./cci.sh
    - acquire_cci_lock

npm-build:
    stage: build
    image: harbor.dx-corp.top/basic/node:8.11.3-stretch
    retry: 3
    tags:
        - ui
    script:
        - yarn config set registry https://registry.dingxiang-inc.com
        - yarn install
        - export NODE_OPTIONS=--max_old_space_size=4096 && npm run build
    artifacts:
        expire_in: 1h
        paths:
            - build/

docker-image:
    stage: package
    dependencies:
        - npm-build
    tags:
        - ctu
    script:
        - download_from_gitlab 848 build/constid-js/index-private.js const-id.js master
        - download_from_gitlab 848 build/constid-js/messager.html  messager.html master
        - download_from_gitlab 848 constid-ui.tar.gz constid-ui.tar.gz master
        - tar -zxvf constid-ui.tar.gz
        - mv constid-ui/constid-admin constid-ui/admin
        - mv constid-ui/constid-js-test constid-ui/demo
        - rm -rf constid-ui/constid-js
        - create_docker_image $PWD/docker.tar.gz
    artifacts:
        expire_in: 1d
        paths:
            - docker.tar.gz

docker-push:
    stage: deploy
    dependencies:
        - docker-image
    tags:
        - ctu
    script:
        - push_to_harbor
